---
title: "Experiment with elevation data"
author: "Johannes Gruenewald"
date: "2024-12-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(sf)
library(geojsonsf)
library(terra)
#library(sp)
library(gstat)
library(tidyverse)
library(ggplot2)
```

```{r}
elev <- terra::rast("../data/hd_elev.tif")
data_temp <- st_read("../data/sensor_data_202407081200_7days.gpkg")
```

```{r}
elev <- terra::project(elev,"EPSG:4326")
crs(elev)
```

```{r}
data_temp <- data_temp %>% 
  filter(!is.na(temperature)) %>%
  group_by(entity_id) %>%
  slice_max(order_by = dateobserved, n = 1) %>% 
  dplyr::select(c(temperature))
```

```{r}
# Add X Y Coordinates to data_temp This is necessary for later steps
data_temp$X <- st_coordinates(data_temp)[,1]
data_temp$Y <- st_coordinates(data_temp)[,2]
```

```{r}
# get elevation at the sites
elevation <- terra::extract(elev,
                             data_temp,
                             buffer=0)
```

```{r}
# unlist elevations to add as column to data
data_temp$elevation <- elevation[,2]
```


```{r}
# Ensure the columns exist in the sf object
if("temperature" %in% colnames(data_temp) & "elevation" %in% colnames(data_temp)) {
  # Create the scatter plot with swapped axes
  ggplot(data_temp, aes(x = temperature, y = elevation)) +
    geom_point(color = "blue", alpha = 0.7) + # Scatter points
    geom_smooth(method = "lm", color = "red", se = TRUE) + # Linear regression line
    labs(
      title = "Correlation Between Temperature and Elevation",
      x = "Temperature (°C)",
      y = "Elevation (meters)"
    ) +
    theme_minimal() # Clean and modern theme
} else {
  print("The columns 'temperature' and 'elevation' are not found in the sf object.")
}
```

